# Generated by Django 3.0.1 on 2020-07-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraga_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Val',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_text', models.CharField(max_length=200)),
                ('roster', models.IntegerField(default=0)),
                ('fraga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Fraga')),
            ],
        ),
    ]
